**Autor:** Gianni S. S. Liveraro

**Última Atualização:** Set/2023

**Descrição:** Notebook interativo para análise exploratória de dados tabelados. Para um arquivo .csv de input, as análises possíveis são:

- **Exploratory Table:** Atributos estatísticos são calculados para todas as features de acordo com o seu tipo (numérica ou categórica): média, desvio-padrão, mediana, intervalo interquartil, min/max, N. de NaN, Frequências e etc.  

- **Exploratory Plots:** Permite plotar gráficos (histogramas, scatterplots, barplots, crosstables e etc) de forma interativa.  

- **Correlation Plots:** Plota duas matrizes de correlação. A primeira com os coeficientes de Spearman para as features numéricas e a segunda com os valores de Chi-Quadrado para as features categóricas.

Um exemplo de uso das funções está incluso na última seção deste Notebook.

Obs.: As funções/bibliotecas utilizadas são importadas do script auxiliar "ExploratoryClass.py". Sem ele, nada funciona.

In [6]:
# Initial Settings
FileName = 'SigmaAnalysisTree'#'MCNewGammasOnlyTree'#'MCNewGammasOnlyTree' # File name, should be a .csv or parquet file!!
StudyName = "TrainingGeneralMLModels"
PROJECT_PATH = '/storage1/liveraro/ML_Strangeness/' # Project main directory path
FILE_PATH = PROJECT_PATH+'Dataset/Processed/{}/{}.parquet'.format(StudyName, FileName)
#FILE_PATH = PROJECT_PATH+'DEV/Gianni/Studies/FindableExercise/{}.parquet'.format(FileName)

In [7]:
# JUST EXECUTE THIS CELL. THERE IS NOTHING TO CHANGE HERE!

# Loading libraries and custom functions/classes!
import sys

sys.path.insert(0,PROJECT_PATH+'Notebooks/')
from ExploratoryClass import *

# Load the dataset
df = pd.read_parquet(FILE_PATH)

# Creating directory to save analysis results
EXPLORATORYANALYSIS_PATH = PROJECT_PATH+'DEV/Gianni/Studies/{}/ExploratoryAnalysis/'.format(StudyName)
os.makedirs(EXPLORATORYANALYSIS_PATH, exist_ok=True)

In [8]:
# Table Settings

## It determines minimum number of unique values to consider a feature as categorical
categorical_threshold = 16  ## You should adjust this threshold based on your data

## Flags:
SaveTable = False # If True, save table as.XLSX file in ../ExploratoryAnalysis
SaveFigures = False # If True, save 1D plots for each feature in ../ExploratoryAnalysis/SavedPlots/

# Creating table
print("Number of entries/rows (dataframe size): ", len(df))
summary_df, sample, categorical_features, numerical_features, ListGoodFeatures  = feature_summary(df, EXPLORATORYANALYSIS_PATH, FileName, categorical_threshold, SavePlots=SaveFigures, SaveTable=SaveTable)
categorical_list, numerical_list = categorical_features.copy(), numerical_features.copy()
summary_df

Number of entries/rows (dataframe size):  96380
 Processing Feature 28 out of 29

,Feature,Dtype,Mean,STD,Median,"IQ (Q1, Q3)","Min, Max",Skewness,Kurtosis,Frequency,N. Zeros,N. Negatives,N. Uniques,N. NaN
0,fPhotonMass,float32,0.33,1.200000e-01,3.217668e-01,"[0.25820666551589966, 0.3909548223018646]","[0.026060234755277634, 1.8427340984344482]",1.11,4.49,"{""0.026060234755277634"":19 (0.0 %)}",0 (0.0 %),0 (0.0 %),77362.0,0 (0.0 %)
1,fPhotonPt,float32,0.17,8.000000e-02,1.757789e-01,"[0.10388605296611786, 0.2437303364276886]","[0.0010220970725640655, 0.2999945878982544]",-0.22,-1.07,"{""0.29819464683532715"":19 (0.0 %)}",0 (0.0 %),0 (0.0 %),77466.0,0 (0.0 %)
2,fPhotonQt,float32,0.08,4.000000e-02,8.554217e-02,"[0.05060232803225517, 0.11837340705096722]","[8.334332960657775e-06, 0.14993023872375488]",-0.22,-1.05,"{""0.14608381688594818"":19 (0.0 %)}",0 (0.0 %),0 (0.0 %),77463.0,22 (0.02 %)
3,fPhotonAlpha,float32,-0.01,2.900000e-01,-8.674326e-03,"[-0.17514381185173988, 0.15268006920814514]","[-5.041167736053467, 3.0393266677856445]",-0.77,17.12,"{""-1.165213704109192"":19 (0.0 %)}",0 (0.0 %),49567 (51.43 %),77593.0,0 (0.0 %)
4,fPhotonRadius,float32,3.10,2.740000e+00,2.188441e+00,"[1.5133808255195618, 3.4713534116744995]","[1.2000149488449097, 52.3088493347168]",3.55,20.36,"{""1.232743263244629"":19 (0.0 %)}",0 (0.0 %),0 (0.0 %),77473.0,0 (0.0 %)
5,fPhotonCosPA,float32,0.98,3.000000e-02,9.897783e-01,"[0.9670073539018631, 0.9972056150436401]","[0.9000088572502136, 1.0]",-1.36,0.84,"{""0.9968874454498291"":19 (0.0 %)}",0 (0.0 %),0 (0.0 %),70867.0,0 (0.0 %)
6,fPhotonDCADau,float32,0.35,2.700000e-01,2.820413e-01,"[0.120915612205863, 0.5306298136711121]","[3.8654384297842626e-06, 0.999940812587738]",0.68,-0.58,"{""0.06687906384468079"":19 (0.0 %)}",0 (0.0 %),0 (0.0 %),77527.0,0 (0.0 %)
7,fPhotonDCANegPV,float32,0.60,1.650000e+00,6.437376e-01,"[-0.18126127123832703, 1.151126742362976]","[-13.73953914642334, 18.156705856323242]",0.25,4.97,"{""2.348419666290283"":26 (0.0 %)}",0 (0.0 %),27732 (28.77 %),71067.0,0 (0.0 %)
8,fPhotonDCAPosPV,float32,-0.61,1.690000e+00,-6.490627e-01,"[-1.1675164699554443, 0.17321302741765976]","[-26.08462142944336, 15.470839500427246]",-0.27,5.55,"{""1.2029796838760376"":20 (0.0 %)}",0 (0.0 %),68617 (71.19 %),70571.0,0 (0.0 %)
9,fPhotonZconv,float32,0.24,5.640000e+00,1.770238e-01,"[-2.9684799313545227, 3.4512136578559875]","[-29.27548599243164, 41.666866302490234]",0.03,1.12,"{""-2.3091557025909424"":19 (0.0 %)}",0 (0.0 %),46642 (48.39 %),77604.0,0 (0.0 %)
10,fPhotonEta,float32,0.01,3.900000e-01,7.941119e-03,"[-0.3016756474971771, 0.31658565253019333]","[-1.408894658088684, 1.3899116516113281]",-0.02,-0.77,"{""-1.313305139541626"":19 (0.0 %)}",0 (0.0 %),47585 (49.37 %),77529.0,0 (0.0 %)
11,fPhotonY,float32,0.01,3.900000e-01,7.941164e-03,"[-0.3016756474971771, 0.31658565253019333]","[-1.408894658088684, 1.3899116516113281]",-0.02,-0.77,"{""-1.3133050203323364"":19 (0.0 %)}",0 (0.0 %),47585 (49.37 %),77577.0,0 (0.0 %)
12,fPhotonPosTPCNSigma,float32,-9.39,9.366000e+01,-9.471201e-01,"[-3.050936698913574, 0.43581216782331467]","[-999.0, 488.4341735839844]",-10.36,106.77,"{""-999.0"":848 (1.0 %)}",0 (0.0 %),64386 (66.8 %),69809.0,0 (0.0 %)
13,fPhotonNegTPCNSigma,float32,-7.89,8.311000e+01,-1.049295e+00,"[-3.2292213439941406, 0.38264060765504837]","[-999.0, 280.9879150390625]",-11.78,137.62,"{""-999.0"":670 (1.0 %)}",0 (0.0 %),65751 (68.22 %),70431.0,0 (0.0 %)
14,fPhotonPosTPCCrossedRows,uint8,108.10,2.944000e+01,1.000000e+02,"[85.0, 137.0]","[0, 152]",-0.09,-0.11,"{""152"":8039 (8.0 %)}",838 (0.87 %),0 (0.0 %),84.0,0 (0.0 %)
15,fPhotonNegTPCCrossedRows,uint8,109.52,2.942000e+01,1.020000e+02,"[85.0, 140.0]","[0, 152]",-0.07,-0.38,"{""152"":8983 (9.0 %)}",655 (0.68 %),0 (0.0 %),84.0,0 (0.0 %)
16,fPhotonPosPt,float32,0.19,6.000000e-02,1.694936e-01,"[0.1496708244085312, 0.20459967479109764]","[0.04191165417432785, 1.2300872802734375]",3.06,17.01,"{""0.1458095908164978"":19 (0.0 %)}",0 (0.0 %),0 (0.0 %),76991.0,0 (0.0 %)
17,fPhotonNegPt,float32,0.19,7.000000e-02,1.710924e-01,"[0.1503259837627411, 0.20947862043976784]","[0.04107612743973732, 1.7111998796463013]",3.48,23.12,"{""0.1466066837310791"":19 (0.0 %)}",0 (0.0 %),0 (0.0 %),77163.0,0 (0.0 %)
18,fPhotonPosEta,float32,0.00,3.900000e-01,4.781404e-03,"[-0.29687488824129105, 0.31001126766204834]","[-0.799943208694458, 0.7999256253242493]",-0.01,-0.87,"{""0.06800246983766556"":19 (0.0 %)}",0 (0.0 %),47756 (49.55 %),77146.0,0 (0.0 %)
19,fPhotonNegEta,float32,0.00,4.000000e-01,3.917367e-03,"[-0.3041086792945862, 0.31479229032993317]","[-0.7999958992004395, 0.799892008304596]",-0.01,-0.90,"{""-0.3660418689250946"":19 (0.0 %)}",0 (0.0 %),47821 (49.62 %),77156.0,0 (0.0 %)
20,fPhotonPosY,float32,0.00,3.900000e-01,4.781380e-03,"[-0.2968740835785866, 0.3100099563598633]","[-0.799937903881073, 0.7999238967895508]",-0.01,-0.87,"{""0.06800205260515213"":19 (0.0 %)}",0 (0.0 %),47756 (49.55 %),77170.0,0 (0.0 %)
21,fPhotonNegY,float32,0.00,4.000000e-01,3.917350e-03,"[-0.3041071593761444, 0.3147915303707123]","[-0.799993097782135, 0.7998916506767273]",-0.01,-0.90,"{""-0.3660397529602051"":19 (0.0 %)}",0 (0.0 %),47821 (49.62 %),77160.0,0 (0.0 %)
22,fPhotonPsiPair,float32,-0.00,6.200000e-01,-1.335443e-04,"[-0.375664584338665, 0.3710143491625786]","[-1.5707963705062866, 1.5707963705062866]",0.01,0.05,"{""1.5707963705062866"":87 (0.0 %)}",0 (0.0 %),48196 (50.01 %),77435.0,0 (0.0 %)
23,fPhotonPosITSCls,int32,NaN,NaN,NaN,"[None, None]","[None, None]",NaN,NaN,"{""4"":31857 ( 33.05 %), ""5"":23962 ( 24.86 %), ""...",None,None,NaN,0 (0.0 %)
24,fPhotonNegITSCls,int32,NaN,NaN,NaN,"[None, None]","[None, None]",NaN,NaN,"{""4"":31920 ( 33.12 %), ""5"":24351 ( 25.27 %), ""...",None,None,NaN,0 (0.0 %)
25,fPhotonPosITSClSize,uint32,68136270.03,4.252389e+07,7.047603e+07,"[42221056.0, 74711040.0]","[0, 268431360]",1.48,4.60,"{""71303168"":2733 (3.0 %)}",26 (0.03 %),0 (0.0 %),23862.0,0 (0.0 %)
26,fPhotonNegITSClSize,uint32,68175456.85,4.035764e+07,7.052151e+07,"[51992832.0, 74662912.0]","[0, 268428288]",1.42,4.69,"{""71303168"":2880 (3.0 %)}",28 (0.03 %),0 (0.0 %),23343.0,0 (0.0 %)
27,fPhotonV0Type,uint8,NaN,NaN,NaN,"[None, None]","[None, None]",NaN,NaN,"{""1"":96355 ( 99.97 %), ""7"":25 ( 0.03 %)}",None,None,NaN,0 (0.0 %)
28,fGammaBDTScore,float32,NaN,NaN,NaN,"[None, None]","[None, None]",NaN,NaN,"{""-1.0"":96380 ( 100.0 %)}",None,None,NaN,0 (0.0 %)

In [17]:
# Cell to create new derived variables
df['IsMotherSigma'] = (df['fPDGCodeMother'] == 3212)
categorical_list.append('IsMotherSigma')
df['NullHypothesis'] = (df['fSelHypothesis'] == 0)
categorical_list.append('NullHypothesis')

In [10]:
# Exploratory plots
Exploratory_Plots(df, numerical_list, categorical_list, EXPLORATORYANALYSIS_PATH)

HBox(children=(VBox(children=(Dropdown(description='x-axis:', options=(None, 'fPhotonMass', 'fPhotonPt', 'fPho…

In [15]:
# Todo esse bloco pra calcular a frequencia de cada categoria
b = Counter(df['fSelHypothesis'].dropna())
total = sum(b.values())
stringaux = "{"
counter = 0
Arraysize = len(b.most_common())
for face, count in b.most_common():
    if counter==(Arraysize-1):
        stringaux = stringaux + "\""+str(face)+"\""+ ":" + str(count) + " ( " + str(round(100*count/total,2)) + " %)"
    else:
        stringaux = stringaux + "\""+str(face)+"\""+ ":" + str(count) + " ( " + str(round(100*count/total,2)) + " %), "
    counter = counter+1
    print()
stringaux = stringaux + "}"
stringaux

'{"1":3479905 ( 91.92 %), "0":196810 ( 5.2 %), "3":41414 ( 1.09 %), "8":36211 ( 0.96 %), "2":22231 ( 0.59 %), "4":4615 ( 0.12 %), "9":1527 ( 0.04 %), "10":1407 ( 0.04 %), "5":701 ( 0.02 %), "6":675 ( 0.02 %), "12":90 ( 0.0 %), "7":75 ( 0.0 %)}'

In [18]:
#pd.reset_option('display.max_rows')
df[df.fPDGCodeMother==3212]

,fPosITSCls,fNegITSCls,fPosITSClSize,fNegITSClSize,fPosTPCRows,fNegTPCRows,fPosTPCSigmaPi,fNegTPCSigmaPi,fPosTPCSigmaPr,fNegTPCSigmaPr,...,fPsiPair,fV0type,fCentrality,fSelHypothesis,fIsLambda,fIsAntiLambda,fIsGamma,fIsKZeroShort,fPDGCodeMother,IsMotherSigma
1748,3,4,85196800,38035456,151,103,3.251102,5.859046,-12.854002,-12.822053,...,1.094768,1,74.5,4,False,False,True,False,3212,True
2915,6,6,69358352,70325312,0,152,-999.000000,9.881161,-999.000000,-9.784485,...,-0.516116,1,8.5,0,False,False,True,False,3212,True
3763,0,0,0,0,152,76,-999.000000,7.256721,-999.000000,9.607872,...,0.457123,7,58.5,0,False,False,True,False,3212,True
2624,4,4,54730752,54804480,152,147,4.962058,9.219376,-12.574466,-10.632338,...,-0.982765,1,68.5,0,False,False,True,False,3212,True
880,0,0,0,0,152,149,6.838527,-999.000000,4.038226,-999.000000,...,-0.058210,7,46.5,4,False,False,True,False,3212,True
3995,2,2,37748736,36700160,95,152,0.611532,5.370833,-13.441918,-12.628187,...,0.007587,1,12.5,2,False,False,True,False,3212,True
3212,2,2,35651584,49283072,152,152,8.276330,7.029226,-11.073449,-12.190604,...,-1.201476,1,23.5,4,False,False,True,False,3212,True
420,2,2,75497472,72351744,152,152,5.770154,7.309719,-7.434824,-11.228879,...,0.685702,1,9.5,4,False,False,True,False,3212,True
1695,4,3,71458816,70516736,93,152,5.010190,4.853639,-10.480797,-12.878621,...,-1.050192,1,5.5,5,False,False,True,False,3212,True
2056,2,3,256901120,37879808,149,143,5.926603,3.821844,-12.531868,-13.194372,...,-0.984868,1,7.5,0,False,False,True,False,3212,True
1829,0,0,0,0,146,152,7.070601,-999.000000,-4.345105,-999.000000,...,-0.277331,7,17.5,0,False,False,True,False,3212,True
1765,3,3,254935040,70451200,98,141,-1.650257,9.564747,-13.740849,-10.743647,...,0.691012,1,32.5,4,False,False,True,False,3212,True
818,4,4,105005056,239878144,152,148,10.426494,4.372587,-9.748972,-13.001289,...,-1.354957,1,67.5,1,False,False,True,False,3212,True
3636,2,2,69206016,71303168,152,133,7.098629,5.092040,-7.869414,-12.923688,...,-0.061966,1,23.5,1,False,False,True,False,3212,True
3356,4,3,70541312,71761920,75,149,-2.690535,3.868516,-13.811398,-12.812445,...,0.154101,1,34.5,4,False,False,True,False,3212,True
1288,2,2,71303168,70254592,102,150,-0.257684,4.665193,-13.630226,-10.409486,...,-0.230966,1,48.5,0,False,False,True,False,3212,True
1684,2,2,36700160,20971520,152,152,8.524076,10.573751,-8.128525,-11.355880,...,-0.114811,1,19.5,4,False,False,True,False,3212,True
2425,4,4,69476352,70533120,147,144,9.311502,6.442079,-7.735000,-11.919877,...,0.196346,1,15.5,4,False,False,True,False,3212,True
432,3,4,78905344,73678848,90,152,2.181030,6.506444,-13.344558,-7.828287,...,-0.290319,1,27.5,0,False,False,True,False,3212,True
1563,4,4,88358912,21184512,102,136,0.609506,4.420938,-13.520216,-13.224319,...,1.320763,1,38.5,4,False,False,True,False,3212,True
165,5,4,69683456,130310144,99,127,3.214097,2.007023,-13.373532,-13.377601,...,1.458807,1,38.5,4,False,False,True,False,3212,True
27,5,5,103037184,35802880,128,152,2.681556,6.661748,-13.228504,-12.547688,...,-0.965756,1,3.5,4,False,False,True,False,3212,True
2576,3,3,69468160,52690944,148,152,6.023248,6.663797,-12.962661,-11.642910,...,0.311146,1,44.5,6,False,False,True,False,3212,True
2383,2,2,102760448,35651584,152,148,6.823763,7.755847,-12.215805,-12.130869,...,0.328068,1,43.5,0,False,False,True,False,3212,True
2452,2,2,37748736,71303168,152,152,4.552568,7.307919,-12.948830,-11.894627,...,0.929508,1,53.5,4,False,False,True,False,3212,True
1421,0,0,0,0,152,144,-999.000000,8.499034,-999.000000,-6.006607,...,0.356949,7,49.5,0,False,False,True,False,3212,True
2610,4,3,36978688,35913728,98,152,-1.379386,7.406925,-13.688406,-10.746451,...,0.801612,1,47.5,4,False,False,True,False,3212,True
531,4,3,120741888,70385664,132,143,1.745190,8.721149,-13.333642,-8.835926,...,1.165792,1,62.5,4,False,False,True,False,3212,True
59,3,4,53739520,54730752,152,128,2.369092,4.453554,-13.242361,-13.274847,...,-0.139776,1,26.5,0,False,False,True,False,3212,True
121,4,3,88358912,71565312,152,84,7.055699,1.705289,-12.275584,-13.491736,...,-0.966902,1,25.5,5,False,False,True,False,3212,True
1861,3,4,101908480,54804480,152,127,2.702959,3.179062,-13.204641,-13.326041,...,0.303423,1,34.5,0,False,False,True,False,3212,True
681,7,7,53682802,52713028,152,84,6.380230,-2.515093,-11.496999,-13.779451,...,-0.851785,1,14.5,4,False,False,True,False,3212,True
277,4,5,52903936,71644928,152,95,8.324057,-0.269474,-12.151331,-13.452748,...,0.907807,1,25.5,5,False,False,True,False,3212,True
2811,4,7,40116224,56763204,147,127,3.582109,0.567250,-13.109877,-13.497483,...,-0.276376,1,27.5,0,False,False,True,False,3212,True
1251,2,2,53477376,53477376,152,152,5.888522,7.654187,-12.130594,-11.015924,...,-1.319001,1,30.5,4,False,False,True,False,3212,True
3419,0,0,0,0,152,146,11.410292,-999.000000,-6.177883,-999.000000,...,-0.167886,7,91.5,0,False,False,True,False,3212,True

In [23]:
#df = df.reset_index()
df[['fPosITSCls', 'fNegITSCls', 'fPosTPCRows' , 'fNegTPCRows', 'fX', 'fY', 'fPxPos', 'fPyPos', 'fPzPos', 'fPxNeg', 'fPyNeg', 'fPzNeg', 'fDCAV0daughters']].iloc[0:3]

,fPosITSCls,fNegITSCls,fPosTPCRows,fNegTPCRows,fX,fY,fPxPos,fPyPos,fPzPos,fPxNeg,fPyNeg,fPzNeg,fDCAV0daughters
0,3,3,152,90,-11.595124,-18.402390,-0.238674,-0.377204,0.136423,-0.083195,-0.132129,0.046976,0.039636
1,4,3,149,152,-3.952118,-20.197016,-0.050129,-0.255651,0.083348,-0.101915,-0.536573,0.180869,0.002713
2,4,7,128,152,-0.054341,0.034349,-0.198999,0.038294,-0.067885,-0.191197,0.123766,-0.021098,0.008609